### Amazon Web Services (AWS) configuration
###########################################

# key - AWS Access Key ID
key: YourKey
# secret - AWS secret access key
secret: YourSecret
# region - Region name (e.g. 'us-east-1', 'us-west-1', 'us-west-2', 'eu-west-1', etc...)
region: eu-west-1
# bucket title
bucket: YourBucket


### Repository configuration ##############
###########################################

# relative or absolute path to your repository
path: ./src